### ISSUE TITLE
How to do for run in dev?

### ISSUE THREAD

**Issue by LeonardoRosaa** [muhibbudins/denomon#4]
Hi! Thanks for repository. 
I have a question... :laughing: I would like run in dev for running a few tests in my machine, how you do?

**Comment by hibuno** [comment]
Hi @LeonardoRosaa,

This tool just only for running and watching change on the files, if your tests are a single file you can use `denomon file_test.ts` or if it has multiple test files you can use `denomon --dir folder_path`.

Thank you

**Comment by LeonardoRosaa** [comment]
@muhibbudins Thanks for answer, but I want say how to do run in developing for example to open a PR with any correction or new feature... that for this, is necessary run first the *denomon* with my changes in my local machine. Sorry for the inconvenience.

**Comment by hibuno** [comment]
I see, sorry for the misunderstanding @LeonardoRosaa. Do you mean the contribution guide? also how to test whether denomon is working properly.

**Comment by LeonardoRosaa** [comment]
Yes, I would like contributing, but is necessary build a setup for developing in my local machine? sure? That said, I would like to know how to do build a this setup?
